version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - LISTEN_PORT=3000
      - OIDC_ISSUER=http://oauth-server:10001

  oauth-server:
    image: node:18
    entrypoint: npx oauth2-mock-server -p 10001 -a oauth-server
    ports:
      - "10001:10001"
